# Generated by Django 3.0.8 on 2020-08-02 12:31

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200802_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_image_path),
        ),
    ]
