# Generated by Django 3.0.8 on 2020-08-13 14:52

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200809_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='/media/products/spade_melting_skull.jpg', null=True, upload_to=store.models.get_image_path),
        ),
    ]
